### ISSUE TITLE
SplitMenus=true 时后台菜单无法点击无效

### ISSUE THREAD

**Issue by 377123** [quarkcms/quark-easy#1]
`// 后台Layout配置
var Admin = &AdminConfig{

	// 应用标题
	Title: App.Name,

	// Logo
	Logo: false,

	// 登录页子标题
	SubTitle: "信息丰富的世界里，唯一稀缺的就是人类的注意力",

	// 使用 IconFont 的图标配置
	IconfontUrl: "//at.alicdn.com/t/font_1615691_3pgkh5uyob.js",

	// layout 的菜单模式,side：右侧导航，top：顶部导航，mix：混合模式
	Layout: "mix",

	// layout 的菜单模式为mix时，是否自动分割菜单
	**SplitMenus: true**,`

SplitMenus=true 时后台菜单无法点击无效

**Comment by tangtanglove** [comment]
感谢反馈，已知的问题，将来有时间修复
